--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TPEimperialPE/AdvancedPlayerCount
build-by-default: true
branches:
- master
projects: 
  AdvancedPlayerCount:
    icon: "icon.png"
... path: ""
